# Generated by Django 6.0.3 on 2026-04-06 16:03

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the todo item', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the todo item (minimum 3 characters)', max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the todo item', verbose_name='description')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether the todo item is completed', verbose_name='is completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the todo item was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the todo item was last updated', verbose_name='updated at')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date and time when the todo item was completed', null=True, verbose_name='completed at')),
                ('image', models.ImageField(blank=True, help_text='Optional image for the todo item', null=True, upload_to='todo_images/%Y/%m/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'db_table': 'todos',
                'ordering': ['-created_at'],
            },
        ),
    ]
