# Generated by Django 6.0.3 on 2026-04-06 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='owner',
            field=models.ForeignKey(default=1, help_text='User who owns this todo item', on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together={('owner', 'title')},
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['owner', 'created_at'], name='todos_owner_i_527115_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['is_completed'], name='todos_is_comp_e9d611_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['created_at'], name='todos_created_6a89a6_idx'),
        ),
    ]
